name: Sync to Gitee

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0   # 必须拉取完整历史

    - name: Set up Git user
      run: |
        git config --global user.name "${{ secrets.GITEE_USER }}"
        git config --global user.email "${{ secrets.GITEE_USER }}@users.noreply.github.com"

    - name: Push to Gitee
      run: |
        git remote add gitee https://${{ secrets.GITEE_USER }}:${{ secrets.GITEE_TOKEN }}@gitee.com/${{ secrets.GITEE_USER }}/promptHub.git
        git push --force gitee main
